veracrypt_executable_path: C:\Program Files\VeraCrypt\

bitwarden:
  url: http://localhost:5000
  password_base64: dGVzdA==
  credential_name: volume_password

volume:
  folder: C:\Users\kamuri\Downloads\test
  name: test
  mount_point: Z
  size: 10M

default_structure:
  - name: common
    children:
      - name: images
      - name: documents
        children:
          - name: pdf
          - name: word
          - name: excel
          - name: powerpoint
          - name: others
      - name: videos
      - name: music
      - name: projects
      - name: others
